# Generated by Django 3.0.8 on 2020-07-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Profile',
        ),
    ]
